name: Deploy Web
on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]   # spustí se jen když změníš něco ve frontend/
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      # instalace a build ve složce frontend
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

      # nasadíme přímo obsah složky dist
      - uses: azure/webapps-deploy@v3
        with:
          app-name: web-genalpha
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: ./frontend/dist
