name: Deploy Web
on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]   # only when frontend/ changes
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      # install and build in frontend/
      - run: npm ci
        working-directory: frontend
      - name: Run unit tests
        run: npm run test
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

      # deploy frontend/dist contents
      - uses: azure/webapps-deploy@v3
        with:
          app-name: web-genalpha
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: ./frontend/dist
